version: "3.2"

services:
  rooms:
    build: 'rooms'
    image: thefirstspine_rooms_image
    container_name: thefirstspine_rooms_container
    networks:
      default:
    volumes:
      - /var/log:/var/log
    ports:
      - "${PORT}:${PORT}"
    tty: true
    env_file:
      - .env

networks:
  default:
    driver: bridge
