version: "3.2"

services:
  rooms_postgres:
    image: postgres:11
    container_name: thefirstspine_rooms_postgres_container
    networks:
      default:
        ipv4_address: ${PG_HOST}
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
      - /var/log:/var/log
    ports:
      - "${PG_PORT}:${PG_PORT}"
    tty: true
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    command: -p ${PG_PORT}
  rooms:
    build: 'rooms'
    image: thefirstspine_rooms_image
    container_name: thefirstspine_rooms_container
    networks:
      default:
    volumes:
      - /var/log:/var/log
    ports:
      - "${PORT}:${PORT}"
    tty: true
    env_file:
      - .env
    depends_on:
      - rooms_postgres

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
